version: '3'

services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: honeypot
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
